### ISSUE TITLE
[Bug]: Service worker causing 500 error with Authjs v5 for Google during repeated sign-ins and sign-outs.

### ISSUE THREAD

**Issue by nunesunil** [serwist/serwist#150]
### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 9.0.1
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5

### Which project is this issue for?

serwist

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

[github.com/nunesunil/serwist-google](https://github.com/nunesunil/serwist-google)

### To reproduce

1. pnpm i
2. pnpm build
3. pnpm start

### Describe the bug

The initial sign-in works fine, but after signing out and signing in repeatedly, it causes a 500 error from the service worker. However, if we remove the integration of withServiceWorker from the nextConfig in next.config.mjs, it works fine.  Server log -

error { error: 'invalid_grant', error_description: 'Bad Request' }
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle OIDC response body error
    at ix (/Users/sunil/Desktop/my-app/.next/server/app/api/auth/[...nextauth]/route.js:377:28205)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i$ (/Users/sunil/Desktop/my-app/.next/server/app/api/auth/[...nextauth]/route.js:377:34125)
    at async iq (/Users/sunil/Desktop/my-app/.next/server/app/api/auth/[...nextauth]/route.js:377:45454)
    at async iV (/Users/sunil/Desktop/my-app/.next/server/app/api/auth/[...nextauth]/route.js:377:50328)
    at async /Users/sunil/Desktop/my-app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/Users/sunil/Desktop/my-app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/Users/sunil/Desktop/my-app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/Users/sunil/Desktop/my-app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/sunil/Desktop/my-app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
[auth][details]: {
  "provider": "google"
}

### Expected behavior

Even with repeated sign-ins and sign-outs, it should work fine.

### Screenshots (if relevant)

<img width="1512" alt="Screenshot 2024-05-30 at 3 08 11 PM" src="https://github.com/serwist/serwist/assets/42139381/654a9106-f999-434f-9713-1a1f7e948c4e">

**Comment by DuCanhGH** [comment]
Can you set your `runtimeCaching` to

```js
[
    {
      matcher: /\/api\/auth\/.*/,
      handler: new NetworkOnly(),
    },
    ...defaultCache,
],
```

and see if that fixes the issue? Thanks!

[A bit more on the problem with using Serwist and Auth.js can be found here](https://github.com/serwist/serwist/discussions/28).
