### ISSUE TITLE
[Bug]: vairous issues in either next.config.js or next.config.mjs

### ISSUE THREAD

**Issue by marcofranssen** [serwist/serwist#39]
### Provide environment information

| package | version |
| ------- | ------- |
| @serwist/next | ^8.4.0 |
| @serwist/precaching | ^8.4.0 |
| @serwist/sw | ^8.4.0 |
| next | ^14.0.4 |
| next-contentlayer | ^0.3.4 |
| contentlayer | ^0.3.4 |

### Which project is this issue for?

None

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/marcofranssen/nextjs-blog/tree/switch-to-serwist

### To reproduce

Create a nextjs project using contentlayer.

### Describe the bug

As soon I switch to `serwist` from `@ducanh2912/next-pwa` it fails. I tried both `next.config.js` and `next.config.mjs` approaches.

When using the `.mjs` approach I'm seeing following error:

```shell
$ pnpm dev

> marcofranssen-nl@0.1.0 dev /Users/marco/code/priv/nextjs-blog
> next dev

   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000
   - Environments: .env

 ○ (serwist) PWA support is disabled.
 ○ (serwist) PWA support is disabled.
 ✓ Ready in 6.8s
Contentlayer config change detected. Updating type definitions and data...
Generated 76 documents in .contentlayer
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${Date.now()}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/generation/generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/markdown'
<w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/markdown as file
<w>  at resolve esm file markdown-wasm/dist/markdown.node.js
<w>  at file dependencies /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at file /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at resolve esm file ./markdown/markdown.js
<w>  at file dependencies /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/index.js
<w>  at file /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.19.4/node_modules/@contentlayer/core/dist/index.js
<w>  at resolve esm file @contentlayer/core
<w>  at file dependencies /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/next-contentlayer@0.3.4_contentlayer@0.3.4_esbuild@0.19.4_next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at file /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/next-contentlayer@0.3.4_contentlayer@0.3.4_esbuild@0.19.4_next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at resolve esm file ./plugin.js
<w>  at file dependencies /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/next-contentlayer@0.3.4_contentlayer@0.3.4_esbuild@0.19.4_next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at file /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/next-contentlayer@0.3.4_contentlayer@0.3.4_esbuild@0.19.4_next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at resolve esm file next-contentlayer
<w>  at file dependencies /Users/marco/code/priv/nextjs-blog/next.config.mjs
<w>  at file /Users/marco/code/priv/nextjs-blog/next.config.mjs
<w>  at resolve commonjs /Users/marco/code/priv/nextjs-blog/next.config.mjs
```

See here the `next.config.mjs`.

```js
import { withContentlayer } from "next-contentlayer";
import withSerwistInit from "@serwist/next";

const withSerwist = withSerwistInit({
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  disable: process.env.NODE_ENV === "development",
});

export default withContentlayer(
  withSerwist({
    …
  })
);
```

I also tried using a regular `next.config.js`.

```js
const withSerwist = require("@serwist/next").default({
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  disable: process.env.NODE_ENV === "development",
});
const { withContentlayer } = require("next-contentlayer");

module.exports = withContentlayer(
  withSerwist({
    …
  })
);
```

This results in following error.

```shell
pnpm dev

> marcofranssen-nl@0.1.0 dev /Users/marco/code/priv/nextjs-blog
> next dev

/Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@serwist+build@8.4.0/node_modules/@serwist/build/dist/index.cjs:65
    glob pattern strings.`,
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/stringify-object@5.0.0/node_modules/stringify-object/index.js from /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@serwist+build@8.4.0/node_modules/@serwist/build/dist/index.cjs not supported.
Instead change the require of index.js in /Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@serwist+build@8.4.0/node_modules/@serwist/build/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/next@14.0.4_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/Users/marco/code/priv/nextjs-blog/node_modules/.pnpm/@serwist+build@8.4.0/node_modules/@serwist/build/dist/index.cjs:13:23) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

The project just compiles and works like before when using `@ducanh2912/next-pwa`.

### Additional information (if relevant)

My repo is private, but I can add a maintainer of the project to troubleshoot, also happy to provide more information if you tell me what debug steps to take to provide more details.

**Comment by DuCanhGH** [comment]
The traceback that appears when using `next.config.mjs` shows that this is on `next-contentlayer` rather than Serwist. It even appears when you don't use Serwist/`@ducanh2912/next-pwa` (checked with `@ducanh2912/next-pwa`'s docs).

As for the CJS issue, it has been fixed in 8.4.1. This was due to us importing `stringify-object`. Preventative measures have also been implemented in the fix.
